ProformaLive/Controllers/AOPProjectController.cs
using ProformaLive.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ProformaLive.Authorization.AuthorizeADAttribute;

namespace ProformaLive.Controllers
{
    [Authorize]
    public class AOPProjectController : Controller
    {

        private ProformaLiveEntities db;
        public AOPProjectController()
        {
            db = new ProformaLiveEntities();
        }

        // GET: AOPProject
        public ActionResult Index()
        {
            //Session["CurrentPage"] = 3;
            return View();
        }

        [HttpGet]
        [AuthorizeAD(Groups = Constants.PAdmin)]
        public JsonResult getAOPProject()
        {
            try
            {
                var obj = db.SP_Get_Master_AOPProject().ToList();
                return Json(new { Message = obj, responseCode = 200 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception Ex)
            {
                return Json(new { Message = "error in the system: (" + Ex.Message + ")", responseCode = 404 }, JsonRequestBehavior.AllowGet);
            }           
        }

        public class objsubmit
        {
            public List<SP_Get_Master_AOPProject_Result> update { get; set; }
            public List<SP_Get_Master_AOPProject_Result> delete { get; set; }
        }

        [HttpPost]
        public JsonResult submitchanges(objsubmit obj)
        {          

            if (obj.update != null)
            {
                foreach (var item in obj.update)
                {
                    if (item.Sysid == 0)
                    {
                        Master_AOPProject row = new Master_AOPProject();
                        row.Name = item.Name;
                        db.Master_AOPProject.Add(row);
                        db.SaveChanges();
                    }
                    else
                    {
                        Master_AOPProject row = db.Master_AOPProject.Single(x => x.Sysid == item.Sysid);
                        row.Name = item.Name;
                        db.SaveChanges();
                    }
                }
            }

            if (obj.delete != null)
            {
                foreach (var item in obj.delete)
                {
                    if (item.Sysid != 0)
                    {
                        Master_AOPProject row = db.Master_AOPProject.Single(x => x.Sysid == item.Sysid);
                        db.Master_AOPProject.Remove(row);
                        db.SaveChanges();
                    }
                }
            }

            return Json("data has been updated successfully", JsonRequestBehavior.AllowGet);
        }
    }
}

ProformaLive/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MECC_ReportPortal.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            //Session["CurrentPage"] = 1;
            return View();
        }
    }
}

ProformaLive/Controllers/ProjectsController.cs
using ProformaLive;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.Configuration;
using System.Security.Principal;
using ProformaLive.Authorization;
using static ProformaLive.Authorization.AuthorizeADAttribute;

namespace MECC_ReportPortal.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private ProformaLiveEntities db;
        public ProjectsController()
        {
            db = new ProformaLiveEntities();
        }
        // GET: Projects
        public ActionResult Index()
        {
            //Session["CurrentPage"] = 3;
            return View();
        }

        [HttpGet]
        public ActionResult validateLogin()
        {
            if (Session["username"] == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    string userID = User.Identity.Name;
                    string username = GetUserFromLdap(userID);
                    Session["username"] = username;
                    Session["userid"] = userID.Replace("ENT\\", "");
                    return Json(username, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("invalid user", JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(Convert.ToString(Session["username"]), JsonRequestBehavior.AllowGet);
            }
        }
               
        public class objclone
        {
            public List<SP_Config_Projects_Result> clone { get; set; }
            public string ID { get; set; }
            public string Name { get; set; }

        }

        [HttpPost]
        public JsonResult cloneproformaproject_fromproforma(string strNewProjectName, string strNewProjectID)
        {
            string strProjectName = Convert.ToString(Session["ProjectName"]);
            var projectid = db.Configure_Project
                .Where(x => x.ProjectName == strProjectName)
                .Select(y => y.ProjectID).ToList();

            string userid = Convert.ToString(Session["userid"]);
            if (projectid.Count > 0)
            {
                db.SP_Clone_Proforma(Convert.ToInt32(projectid[0]), strNewProjectID, strNewProjectName, userid);
            }

            return Json("cloning has been done successfully!", JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public JsonResult getmasterproforma(string strProjectID)
        {
            var obj = db.SP_Get_PrimaryProjectData(strProjectID).ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult swapprojects(int intPrimaryProjectID, int intSecondaryProjectID)
        {
            var obj = db.SP_Get_SwapProjects(intPrimaryProjectID, intSecondaryProjectID);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult cloneproformaproject(objclone obj)
        {
            string userid = Convert.ToString(Session["userid"]);
            string status = "";
            if (obj.clone != null)
            {
                foreach (var item in obj.clone)
                {
                    var objstatus = db.SP_validate_CloneProject(obj.ID).ToList();
                    if(objstatus != null && objstatus[0] == "False")
                    {
                        db.SP_Clone_Proforma(item.ProjectID, obj.ID, obj.Name, userid);
                        status = "cloning has been done successfully!";
                    }
                    else
                    {
                        status = "Invalid ProjectID";
                    }                    
                }
            }

            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult createnewproforma(int ID, string strProjectID, string strProjectName,string strUserID)
        {
            string strMessage = "";
            var satus = db.Configure_Project
                    .Where(x => x.ProjectNumber == strProjectID)
                    .Select(y => y.ProjectID).ToList();

            if(satus.Count == 0)
            {
                var obj = db.SP_CreateNew_Proforma(ID, strProjectID, strProjectName, strUserID);                
                strMessage = "Success";
            }
            else
            {
                strMessage = "Project ID already exists!";
            }

            var projectid = db.Configure_Project
                        .Where(x => x.ProjectNumber == strProjectID)
                        .Select(y => y.ProjectID).ToList();

            return new JsonResult { Data = new { Message = strMessage, Status = projectid } };            
        }

        [HttpPost]
        public JsonResult validateuser(string strUserID)
        {
            string username = GetUserFromLdap(strUserID);
            return Json(username, JsonRequestBehavior.AllowGet);
        }
                
        [HttpGet]
        [AuthorizeAD(Groups = Constants.PAdmin)]
        public JsonResult getProjects()
        {
            try
            {
                var obj = db.SP_Config_Projects().ToList();
                return Json(new { Message = obj, responseCode = 200 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception Ex)
            {
                return Json(new { Message = "error in the system: (" + Ex.Message + ")", responseCode = 404 }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult updatemasterdata(string strtype, string strvalue)
        {
            Temp_ProjectMaster tp = new Temp_ProjectMaster();
            tp.Type = strtype;
            tp.Value = strvalue;
            db.Temp_ProjectMaster.Add(tp);
            db.SaveChanges();
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getCapitalGRPType()
        {
            var obj = db.SP_Config_Projects_CapitalGRPType().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getFunded()
        {
            var obj = db.SP_Config_Projects_Funded().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getInPLAN()
        {
            var obj = db.SP_Config_Projects_InPLAN().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getParentChild()
        {
            var obj = db.SP_Config_Projects_ParentChild().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getProjectCategory()
        {
            var obj = db.SP_Config_Projects_ProjectCategory().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult submitchanges(objsubmit obj)
        {
            string userID = Convert.ToString(Session["userid"]);

            if (obj.update != null)
            {
                var projectdata = obj.update;

                var subquery = projectdata.Select(y => new { ProjectNumber = y.ProjectNumber, ProjectName = y.ProjectNumber }).ToList();
                var query = subquery.GroupBy(x => x.ProjectNumber)
                            .Where(g => g.Count() > 1)
                            .Select(y => new { Element = y.Key, Counter = y.Count() })
                            .ToList();

                if (projectdata.Select(x => x.ProjectNumber).Distinct().Count() != projectdata.Count)
                {
                    string strDuplicateString = "";
                    foreach (var item in query)
                    {
                        strDuplicateString = strDuplicateString + "," + item.Element;
                    }

                    return Json(new { Message = strDuplicateString.Substring(1) + " - Project number already used, please enter different project number", responseCode = 404 }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    foreach (var item in obj.update)
                    {
                        if (item.ProjectID == 0)
                        {
                            Configure_Project row = new Configure_Project();
                            row.ProjectName = item.ProjectName;
                            row.ProjectNumber = item.ProjectNumber;
                            row.PMNetworkID = item.PMNetworkID;
                            row.PMName = GetUserFromLdap(item.PMNetworkID);
                            row.ProjectCategory = item.ProjectCategory;
                            row.Status = item.Status;                            
                            row.WBSElement = item.WBSElement;
                            row.CapitalExpenditureWBS = item.CapitalExpenditureWBS;
                            row.GPSProjectNumber = item.GPSProjectNumber;
                            row.Program = item.Program;
                            row.BusinessUnit = item.BusinessUnit;
                            row.PeriodBurdenExpense = item.PeriodBurdenExpense;
                            row.SettlementCostCenter = item.SettlementCostCenter;
                            row.SettlementCostCenterName = item.SettlementCostCenterName;
                            row.SettlemnetSummary = item.SettlemnetSummary;
                            row.EndingBusinessUnit = item.EndingBusinessUnit;
                            row.FundingSource = item.FundingSource;
                            row.SourceCard = item.SourceCard;
                            row.InPLAN = item.InPLAN;

ProformaLive/Controllers/indexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Principal;
using System.Web.Security;
using System.Configuration;
using System.DirectoryServices.AccountManagement;
using ProformaLive.Authorization;
using static ProformaLive.Authorization.AuthorizeADAttribute;

namespace ProformaLive.Controllers
{
    [Authorize]
    public class indexController : Controller
    {
        private ProformaLiveEntities db;
        public indexController()
        {
            db = new ProformaLiveEntities();
        }
        // GET: index
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult updateprojectname(int strProjectID)
        {
            var objProjectData = db.Configure_Project.Where(x => x.ProjectID == strProjectID)
                .Select(i => new { i.ProjectID, i.ProjectNumber, i.ProjectName }).ToList();

            Session["ProjectName"] = objProjectData[0].ProjectName;
            return Json(objProjectData, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public JsonResult getprojectlist()
        {
            var obj = db.SP_Get_Projects().ToList();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        [AuthorizeAD(Groups = Constants.PAdminUsers)]
        public JsonResult CreateUserProfile()
        {
            try
            {
                //initialize domain variables.
                string domain = ConfigurationManager.AppSettings["Domain"];
                string adminUserProfileid = ConfigurationManager.AppSettings["AdminUserRoles"];

                userProfile up = new userProfile();
                string userID = User.Identity.Name;
                var userProfile = GetUserFromLdap();

                if (userProfile != null)
                {
                    up.isAdmin = userProfile.Item2;
                    up.userID = userID.Replace(domain, "");
                    up.userName = userProfile.Item1;

                    //will remove this code------------------------
                    Session["username"] = userProfile.Item1;
                    Session["userid"] = userID.Replace(domain, "");
                    //---------------------------------------------
                }

                return Json(new { Message = up, responseCode = 200 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception Ex)
            {
                return Json(new { Message = "error in the system: (" + Ex.Message + ")", responseCode = 404 }, JsonRequestBehavior.AllowGet);
            }
        }

        public Tuple<string, bool> GetUserFromLdap()
        {
            //initialize service account variables.
            string serviceAccountID = ConfigurationManager.AppSettings["ServiceAccountID"];
            string servicePassword = ConfigurationManager.AppSettings["ServicePassword"];
            string serviceDomain = ConfigurationManager.AppSettings["ServiceDomain"];
            string adminUserProfileid = ConfigurationManager.AppSettings["AdminUserRoles"];

            using (var context = new PrincipalContext(ContextType.Domain, serviceDomain, serviceAccountID, servicePassword))
            {
                var user = UserPrincipal.FindByIdentity(context, User.Identity.Name);

                var userPrincipal = UserPrincipal.FindByIdentity(
                                       context,
                                       IdentityType.SamAccountName,
                                       User.Identity.Name);

                bool isAdminUser = userPrincipal.IsMemberOf(context, IdentityType.Name, adminUserProfileid);

                if (user != null)
                {
                    var userProfile = new Tuple<string, bool>(user.Name, isAdminUser);
                    return userProfile;
                }
            }
            return null;
        }

        //initialize user profile.
        public class userProfile
        {
            public bool isAdmin { get; set; }
            public string userID { get; set; }
            public string userName { get; set; }
        }

    }
}

ProformaLive/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @*Created BY: Ashok Kallagunta
        Created On: 12 06 2020*@
    <!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 11]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content="ProformaLive">
    <meta name="author" content="Medtronic Pvt Ltd." />
    <link rel="icon" href="~/assets/images/favicon.png" type="image/gif" sizes="16x16">

    <title>ProFormaLive</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="~/assets/scripts/angular.min.js"></script>
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/css/proforma.css?ID=6600" rel="stylesheet" />
    <link href="~/assets/css/delete-confirmation.css?ID=6300" rel="stylesheet" />    
</head>
<body style="background-color:#edf7ff; overflow-x: hidden;" ng-app="MECC">
    <nav style="background-color: #01254e !important; padding-bottom: 0px; padding-top: 0px; " class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" style="font-weight: bold;" href="@Url.Action("Index", "index")">
                <img height="26" src="~/assets/images/newlogo.png" />
            </a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0 float-left ml-5">
                <li id="menudashboard" class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Dashboard")">
                        <i class="fa fa-area-chart" aria-hidden="true"></i>&nbsp;&nbsp;Dashboard
                    </a>
                </li>
                <li id="menuresource" class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Resource")">
                        <i class="fa fa-th" aria-hidden="true"></i>&nbsp;&nbsp;Proforma
                    </a>
                </li>
                <li id="menuassignments" class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Assignments")">
                        <i class="fa fa-th" aria-hidden="true"></i>&nbsp;&nbsp;Assign-Live
                    </a>
                </li>
                <li id="mastermenu" style="display:none;" class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-database" aria-hidden="true"></i>&nbsp;&nbsp;Master
                    </a>
                    <div class="dropdown-menu fade-up" style="border-bottom: 1px solid #939fab;" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Index", "Projects")"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;&nbsp;Project</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "AOPProject")"><i class="fa fa-cube" aria-hidden="true"></i>&nbsp;&nbsp;5Yr Capital Item Master</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "ProjectChargeBack")"><i class="fa fa-braille" aria-hidden="true"></i>&nbsp;&nbsp;Project Charge Back</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "ConfigureRateCard")"><i class="fa fa-usd" aria-hidden="true"></i>&nbsp;&nbsp;Configure Rate Card</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "Config_Snapshot")"><i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp;&nbsp;Configure Snapshot</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "notification")"><i class="fa fa-bell" aria-hidden="true"></i>&nbsp;&nbsp;Notification Panel</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>
        </div>
        <div id="masterHelpCenter" class="panelhelpbox">            
            <span class="notificationlabel pull-right"><i class="fa fa-info-circle" aria-hidden="true"></i></span>
        </div>
        <div id="navbarTogglerDemo02" class="panelnotificationbox">
            <ul class="nav pull-right">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="padding-left:10px !important; padding-right:5px !important; color:white;" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span id="notificationtotal" class="notificationspan"></span>
                    </a>
                    <div id="notificationlistbody" style="left: -33px; width: 435px;" class="dropdown-menu fade-up" aria-labelledby="navbarDropdownMenuLink">
                    </div>
                </li>
            </ul>
            <span class="notificationlabel pull-right"><i class="fa fa-bell-o" aria-hidden="true"></i></span>
        </div>
        <div id="navbarTogglerDemo01" style="background-color: #223b54; padding-left: 15px;">
            <ul id="userprofilepanel1" style="display:none;" class="nav pull-right">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color: white; border-left: 1px solid #223b54 !important; font-weight: 500; font-size: 12px; padding-left: 10px !important" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span id="loginusername">validating user..</span>
                    </a>
                    <div style="left: -35px; width: 267px;" class="dropdown-menu fade-up" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#"><i class="fa fa-user-secret" aria-hidden="true"></i>&nbsp;&nbsp;Role: <span id="roles"></span></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "index")"><i class="fa fa-unlock" aria-hidden="true"></i>&nbsp;&nbsp;Log Out</a>
                    </div>
                </li>
            </ul>
            <span id="userprofilepanel2" style="display: none; color: #ffffff; padding-top: 4px; font-size: 20px; " class="pull-right"><i class="fa fa-user-circle-o"></i></span>
        </div>
    </nav>

    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/assets/scripts/Layout.js?ID=2300"></script>

</body>
</html>